<?php $tiramizoo = $this->getTiramizooOrder(); ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo __('Details') ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
	    <div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><?php echo __('Tracking URL') ?></td>
						<td class="value"><input type="text" class="input-text" value="<?php echo $tiramizoo->getTrackingUrl() ?>"/></td>
					</tr>
					<tr>
						<td class="label"><?php echo __('External ID') ?></td>
						<td class="value"><input type="text" class="input-text" value="<?php echo $tiramizoo->getExternalId() ?>"/></td>
					</tr>					
					<tr>
						<td class="label"><?php echo __('API Request') ?></td>
						<td class="value"><textarea><?php echo print_r(json_decode($tiramizoo->getApiRequest())) ?></textarea></td>
					</tr>
					<tr>
						<td class="label"><?php echo __('API Response') ?></td>
						<td class="value"><textarea><?php echo print_r(json_decode($tiramizoo->getApiResponse())) ?></textarea></td>
					</tr>					
				</tbody>
			</table>
		</div>
    </div>
</div>