<?php
/**
 * This file is part of the Tiramizoo_Shipping magento plugin.
 *
 * LICENSE: This source file is subject to the MIT license that is available
 * through the world-wide-web at the following URI:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category  module
 * @package   Tiramizoo_Shipping
 * @author    Tiramizoo GmbH <support@tiramizoo.com>
 * @copyright Tiramizoo GmbH
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

$product = $this->getProduct();

?>

<div class="entry-edit custom-options product-custom-options">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Tiramizoo') ?></h4>
    </div>

	<div class="fieldset fieldset-wide" id="tiramizoo_group">
	    <div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><label for="tiramizoo_enable"><?php echo $this->__('Is enable') ?></label></td>
						<td class="value">
							<select id="tiramizoo_enable" name="tiramizoo_enable">
							<?php
								$options = Mage::getModel('tiramizoo/entity_attribute_source_enable')
									->getAllOptions();
							foreach ($options as $option): ?>
								<option value="<?php echo $option['value'] ?>" <?= ($product->getData('tiramizoo_enable') == $option['value']) ? 'selected="selected"' : null ?>><?php echo $option['label'] ?></option>
							<?php endforeach; ?>
							</select>
						</td>
						<td class="scope-label"><span class="nobr"></span></td>
					</tr>

					<tr>
						<td class="label"><label for="tiramizoo_packed_individually"><?php echo $this->__('Packed individually') ?></label></td>
						<td class="value">
							<select id="tiramizoo_packed_individually" name="tiramizoo_packed_individually">
							<?php
								$options = Mage::getModel('tiramizoo/entity_attribute_source_packed')
									->getAllOptions();
							foreach ($options as $option): ?>
								<option value="<?php echo $option['value'] ?>" <?= ($product->getData('tiramizoo_packed_individually') == $option['value']) ? 'selected="selected"' : null ?>><?php echo $option['label'] ?></option>
							<?php endforeach; ?>
							</select>
						</td>
						<td class="scope-label"><span class="nobr"></span></td>
					</tr>

					<?php
					$tiramizooProduct = Mage::getModel('tiramizoo/product', $product);
					$dimensions = $tiramizooProduct->getDimensions();

					if ($dimensions): ?>
					<tr>
						<td class="label"><label for="meta_keyword"><?php echo $this->__('Dimensions') ?></label></td>
						<td class="value">
							<table>
							<tr>
								<td><?php echo $this->__('From') ?>
						<?php
							switch($dimensions['destination_type']) {
								case 'product':
									echo $this->__('product');
									break;
								case 'category':
									$category = Mage::getModel('catalog/category')->load($dimensions['destination_id']);
								echo $this->__('category') . ': <strong>'.$category->getName().'</strong>';
									break;
								case 'config':
								echo $this->__('configuration');
									break;
							}
						?>
								</td>
							</tr>
						<?php
							foreach(array('weight', 'width', 'height', 'length') as $var): ?>
								<tr>
									<td><strong><?= $this->__(ucwords($var)) ?></strong>: <?= $dimensions[$var] ?></td>
								</tr>
						<?php endforeach; ?>
							</table>
						</td>
						<td class="scope-label"><span class="nobr"></span></td>
					</tr>
					<?php endif; ?>

					<tr>
						<td class="label"><label for="meta_keyword"><?php echo $this->__('Is available') ?></label></td>
						<td class="value">
						<?php if (!$tiramizooProduct->isAvailable()): ?>
							<span style="color: #f00">
								<?php echo __('Product is not available to Tiramizoo delivery.') ?><br>
								<?php if($tiramizooProduct->isDisable()) foreach ($tiramizooProduct->getDisableIds() as $type => $ids): ?>
									<?php if (count($ids)): ?>
										<?= $type.': '.implode(', ', $ids).'<br>' ?>
									<?php endif; ?>
								<?php endforeach; ?>
							</span>
						<?php else: ?>
							<span><?php echo __('Product is available to Tiramizoo delivery.') ?></span>
						<?php endif; ?>
						</td>
						<td class="scope-label"><span class="nobr"></span></td>
					</tr>

					<tr>
						<td class="label"><label for="meta_keyword"><?php echo $this->__('Is packed individually') ?></label></td>
						<td class="value">
							<span>
								<?= !$tiramizooProduct->isPackedIndividually() ?  $this->__('No') :  $this->__('Yes') ?><br>
							</span>
						</td>
						<td class="scope-label"><span class="nobr"></span></td>
					</tr>

				</tbody>
			</table>
        </div>
    </div>
</div>